name: Main workflow
on:
  workflow_dispatch:

jobs:
  build-test-jar:
    runs-on: ubuntu-latest
    container:
      image: clojure:temurin-11-lein
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - run: lein test
      - run: lein jar